apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: concerned-pony-dotnet-basic
  janus-idp.io/tekton: concerned-pony-dotnet-basic
  backstage.io/kubernetes-id: concerned-pony-dotnet-basic
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: concerned-pony-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
